### ISSUE TITLE
Add lint tests

### ISSUE THREAD

**Issue by ankita240796** [oppia/oppiabot#103]
Enforce lint tests in oppiabot repo.

**Comment by anandwana001** [comment]
@ankita240796 Is this issue is about adding Lint checks for Js files, just like `js_ts_linter.py` we have in oppia?

**Comment by vojtechjelinek** [comment]
@anandwana001 Yep, primary enforce some basic checks for JS files.

**Comment by anandwana001** [comment]
@vojtechjelinek Ok,
So, what I understand from here is:
1. Add eslint to project
2. Fix the current lint issues and send PR

or does this include adding eslint to pre-commit also? 

Could you help me out here as I am new to Js things?

**Comment by vojtechjelinek** [comment]
I think you can start with the first two steps, we can add pre-commit stuff later.

**Comment by anandwana001** [comment]
@jameesjohn Does this Q&a and .json file are correct while setting up the eslint `eslint --init` ?

<img width="808" alt="Screenshot 2020-10-13 at 15 34 51" src="https://user-images.githubusercontent.com/25057618/95846956-bdaeaa80-0d69-11eb-8175-d6d87e6fe66e.png">

`.eslintrc.json`

```
{
    "env": {
        "commonjs": true,
        "es2020": true,
        "node": true
    },
    "extends": "eslint:recommended",
    "parserOptions": {
        "ecmaVersion": 11
    },
    "rules": {
        "indent": [
            "error",
            4
        ],
        "linebreak-style": [
            "error",
            "unix"
        ],
        "quotes": [
            "error",
            "single"
        ],
        "semi": [
            "error",
            "always"
        ]
    }
}

```

**Comment by jameesjohn** [comment]
1 is fine. We should lint single quotes.
2: We should enforce double-quotes for JSON files.
3. Yes, we should lint brackets.

**Comment by anandwana001** [comment]
I will be sending sub PR's as in 1 PR the changes are going very big. 
Also, could you please add hacktoberfest label to this issue?

**Comment by vojtechjelinek** [comment]
@anandwana001 hacktoberfest label on thiss issue would not help to cout the PRs, but we will amrk your created PRs with `hacktoberfest-accepted` once they are merged/approved.

**Comment by anandwana001** [comment]
@vojtechjelinek please assign the issue to me, as it will prevent conflict if other contributors looks here.

**Comment by anandwana001** [comment]
@jameesjohn 
Regarding the file `actions_build/index.js` why are we having `/******/` such blocks at a lot of places?

**Comment by jameesjohn** [comment]
The `actions_build/index.js` file is auto-generated. It should be excluded from the lint checks.

**Comment by vojtechjelinek** [comment]
@anandwana001 Hi, will you continue working on this?

**Comment by anandwana001** [comment]
@vojtechjelinek isn't all the files are done?

**Comment by anandwana001** [comment]
[x] actions package
[x] lib package
[x] spec package
