### ISSUE TITLE
Oppiabot should tag PRs with builds passing but last commit > 2 days ago

### ISSUE THREAD

**Issue by ankita240796** [oppia/oppiabot#117]
Oppiabot should tag PRs with builds passing but last commit > 2 days ago, with a warning message / label saying “build might be stale, please update from develop”. Then reviewers/authors can take a closer look, and if someone introduces a new check, they can look at PRs with this label and restart the checks if it makes sense.

**Comment by vojtechjelinek** [comment]
@jameesjohn Hi, I have changed the priority of this since we want this resolved as the core maintainers.
