### ISSUE TITLE
[High priority] Some of Oppiabot's webhook events are deprecated & will soon stop working

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppiabot#120]
See https://developer.github.com/changes/2020-04-15-replacing-the-installation-and-installation-repositories-events/ for context. There will be a brownout on September 1 for these events, and on October 1 they will stop working.

**Comment by ankita240796** [comment]
We don't these two webhook events anywhere in the oppiabot codebase, so no change is required from our end.
