### ISSUE TITLE
New Feature: Reminders for PRs Changing E2E Tests

### ISSUE THREAD

**Issue by U8NWXD** [oppia/oppiabot#122]
# Context and Motivation

The E2E team has been introducing new expectations for PRs that modify the E2E tests, for example rerunning the changed tests 5 times to make sure they aren't flaky. Using Oppiabot to leave reminders on these PRs would help contributors remember these new processes.

# Desired Behavior

Oppiabot leaves a comment on every PR that affects the E2E tests. These are all the files owned by U8NWXD in the CODEOWNERS file. This comment should include a list of reminders of the codeowner checks [documented in the wiki](https://github.com/oppia/oppia/wiki/End-to-End-Tests#codeowner-checks). For example:

> * You will need to provide screenshots showing that the tests aren't flaky after your changes.
> * All constants should be in all-caps.
> * All element selectors need to be at the top of the file except for certain cases in utility files and with chained selectors.
> * Everything that requires a globally unique name should be given a reliably unique name.
> * All `it` blocks should be independent from each other.
> * Use `waitFor` functions before interacting with any element, or use a utility from the `actions.js` file.
> * No await keywords for `.first()`, `.last()` or `.get(i)` calls.
> * Put reused or generally useful code in functions.
> * Variables should be named as nouns, and functions should be named as verbs.
> * All HTML classes you reference in root selectors in the tests should begin with protractor-test-.
> 
> For more details, see the [E2E test wiki page](https://github.com/oppia/oppia/wiki/End-to-End-Tests#codeowner-checks)

**Comment by BenHenning** [comment]
Some of these checks might better fit as CI checks rather than something Oppiabot enforces (see https://github.com/oppia/oppia-android/pull/1729 for something we're introducing on the Android side). In particular, I think the demarcation should be:
- Static analysis checks & code enforcement checks should be enforced using CI
- Process enforcement (e.g. branch naming, PR format, etc.) should be enforced with Oppiabot

@jameesjohn & @ankita240796: what are your thoughts here?

**Comment by U8NWXD** [comment]
@BenHenning sorry if the issue description was unclear; I did not mean to ask that Oppiabot enforce any of the listed practices. The e2e team will enforce them when we do code reviews, and we are looking to add them to the linters. The goal here is to have Oppiabot remind contributors to check that their PRs follow these practices, similarly to how the PR template has a checklist of reminders like running the karma and lint tests locally. The reason to use Oppiabot is that not all PRs need these reminders; only those that modify the e2e tests do

**Comment by U8NWXD** [comment]
Nope, I'm closing it
