### ISSUE TITLE
Android Feature: Update contributors about pending PRs

### ISSUE THREAD

**Issue by rt4914** [oppia/oppiabot#129]
Currently in Oppia-Android, we follow up with the inactive contributors by following these steps:
1. Follow up with student after 7 days of no-activity by commenting on issue and sending an email.
2. If they reply within next 7 days, great, else after 7 days (2 weeks at this point from start), close the PR and mark student as lapsed.

Instead this follow-up process should be automated via oppia-bot.

**Comment by rt4914** [comment]
@BenHenning

**Comment by BenHenning** [comment]
There are two parts here that might not be straightforward for Oppiabot:
- Sending the email to ping the student: is an at-mention not sufficient here?
- Marking a student as lapsed: perhaps just at-mentioning the team lead and/or onboarding contributor would be sufficient?

@jameesjohn / @ankita240796 how does this relate to the existing Oppia web onboarding process? This seems like something that could work similarly for both projects.

**Comment by rt4914** [comment]
> There are two parts here that might not be straightforward for Oppiabot:
> 
> * Sending the email to ping the student: is an at-mention not sufficient here?
at-mention should also work as it will automatically send emails too from Github side.


> * Marking a student as lapsed: perhaps just at-mentioning the team lead and/or onboarding contributor would be sufficient?

Your suggestion can also work easily. I have just mentioned the current manual process that we follow. I think at-mentions in both cases can work easily.

**Comment by jameesjohn** [comment]
> @jameesjohn / @ankita240796 how does this relate to the existing Oppia web onboarding process? This seems like something that could work similarly for both projects.

I think @showtim3 will be able to help here

**Comment by jameesjohn** [comment]
I think the mentions will suffice, however, but I need confirmation from @Showtim3

**Comment by vojtechjelinek** [comment]
@rt4914 @BenHenning I remember you mentioning that you have already implemented something for notifying your onboarders about new contributors? Is that true? Does this issue still stand?

**Comment by rt4914** [comment]
> @rt4914 @BenHenning I remember you mentioning that you have already implemented something for notifying your onboarders about new contributors? Is that true? Does this issue still stand?

@vojtechjelinek There is only one thing that I know which is we have a Discord Channel and @BenHenning has implemented bots which pings in the channel whenever a contributor does any activity on github. It can be comment, issue, PRs, etc. This channel does help me in knowing whats going on. 
@BenHenning Can add more details.

**Comment by seanlip** [comment]
Is there actually an oppiabot todo here? If so, @rt4914, could you please clarify exactly what needs to be implemented by oppiabot?

If there is still something to implement here, I would suggest discussing with @DubeySandeep so that we can do a unified implementation for Web and Android as far as possible.

**Comment by seanlip** [comment]
It's not clear that there's a todo for oppiabot here. Closing.
