### ISSUE TITLE
Alert onboarding team based on contributor activity

### ISSUE THREAD

**Issue by jameesjohn** [oppia/oppiabot#134]
If there are contributors who are not listed in either the onboarding tracker or on the CLA,  alert the onboarding team.
This should be done for both issues and pull requests, using probot.

**Comment by nlok5923** [comment]
@jameesjohn sir i would like to work on this issue.

**Comment by nlok5923** [comment]
@jameesjohn @vojtechjelinek  sir i would like to work on this issue.

**Comment by nlok5923** [comment]
@jameesjohn @vojtechjelinek please can you let me know in what way i need to alert onboarding will it be via tagging onboarding team at open pr or issue or something else.

**Comment by jameesjohn** [comment]
Yes.
This should be when the contributor creates a pull request, and oppiabot can't find them in the CLA sheet and the onboarding tracker.

But we don't have access to the onboarding tracker @vojtechjelinek, can you help with this?

**Comment by vojtechjelinek** [comment]
@jameesjohn You will probably need to ask Sean for access to the onboarding sheet.

**Comment by jameesjohn** [comment]
Right.
For now, @nlok5923, create a new .env variable,  `ONBOARDING_SHEET_ID` in your pull request to store the onboarding sheet id. And write your function to use the sheet id to get the contents of the spreadsheet.

See https://github.com/oppia/oppiabot/blob/959b59c9ccc6cd1494b249f6b1fa11176258bbfc/lib/checkIssueAssignee.js#L27-L44 for an example of authenticating and fetching data from the spreadsheet.

**Comment by nlok5923** [comment]
@jameesjohn sir thanks for the clue.

**Comment by seanlip** [comment]
Closing because this is actually not needed by either the Web or Android dev workflow teams.
