### ISSUE TITLE
Clarify the reason for why a PR is being closed.

### ISSUE THREAD

**Issue by seanlip** [oppia/oppiabot#147]
Per https://github.com/oppia/oppia/pull/11042#issuecomment-715602948, would it be possible to separate out the error messages for the following specific cases:

- PR was made from a develop branch
- PR was made from a branch whose name is prefixed with develop
- PR was made from a branch whose name is prefixed with release
- PR was made from a branch whose name is prefixed with test

This will help prevent the confusion that was noted in https://github.com/oppia/oppia/pull/11042#issuecomment-715603717.

**Comment by BenHenning** [comment]
Out of curiosity, why do we disallow branches that start with 'test'? I understand the reason to prohibit the other two, but this one isn't clear to me. Is it to basically avoid cases like 11042 where people create intentional test branches?

**Comment by seanlip** [comment]
It's because we use those branches for test deployments.

**Comment by BenHenning** [comment]
Ah, is that something new in the last couple years? I haven't kept up closely with the web release process.

**Comment by HarshKhilawala** [comment]
@jameesjohn I would like to work on this! 
 @vojtechjelinek !

**Comment by riyasingh1004** [comment]
I would like to work on this issue

**Comment by AkshadK7** [comment]
I would also like to work on this issue and help make the PRs more Reasonable.

**Comment by vojtechjelinek** [comment]
@AkshadK7 Sorry, this is already taken but you can take a look into #187

**Comment by Suhail-BW** [comment]
@vojtechjelinek  I know this is not the right place to ask but i am absolutely new here, what is the best way to communicate with other contributors.

**Comment by hardikkat24** [comment]
@Suhail-BW Hello. Here is a [link](https://gitter.im/oppia/oppia-chat) to gitter where you can communicate with others. Also have a look at the [wiki](https://github.com/oppia/oppia/wiki).

**Comment by Mayank-gaur** [comment]
Hi!  Can  you please assign me to any task in this issue? I want to work on this issue.

**Comment by vojtechjelinek** [comment]
@Mayank-gaur Riya is already working on this issue.

**Comment by Mayank-gaur** [comment]
@jameesjohn  @vojtechjelinek  I am new to the oppiabot, can you please suggest me some good first issues to start with? I am not able to find any unassigned issues actually. Do you know any?

**Comment by jameesjohn** [comment]
Hi @Mayank-gaur, the available issues are not new-contributor friendly. I suggest taking a look at the good first issues on [oppia/oppia](https://github.com/oppia/oppia).

**Comment by Mayank-gaur** [comment]
@jameesjohn I have looked at oppia issues, and I have submitted a PR also.(It is being reviewed and I think is close to getting merged also). What I meant is I want to learn about oppiabot and start contributing to it. Can you please guide me how can i begin this? I have installed oppiabot.

**Comment by riyasingh1004** [comment]
@vojtechjelinek I think this issue must be closed as the PR #196 has been merged for this issue.

**Comment by vojtechjelinek** [comment]
Thanks a lot Riya!
