### ISSUE TITLE
Bug in owners message

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppiabot#149]
Oppiabot's "new owners" message is confusing, see: https://github.com/oppia/oppia/pull/11084#issuecomment-719022812. Specifically:
1. It's copying unrelated things from the owners file (comments)
2. Why does Vinita care about this? Just because she's the initial reviewer? Sandeep actually has to approve the change, so it seems more relevant to him as the codeowner of the changed file.

**Comment by HarshKhilawala** [comment]
@vojtechjelinek @jameesjohn Please assign me this issue.

**Comment by jameesjohn** [comment]
Done.
You can start working on this.
