### ISSUE TITLE
Add line comments to PRs whenever a pylint pragma is encountered in PR diff

### ISSUE THREAD

**Issue by apb7** [oppia/oppiabot#15]
A bot similar to this: https://github.com/koddsson/eslint-disable-probot can be implemented by changing the `eslint-disable` pragma to `pylint-disable` pragma.

This check is not fool-proof since it works on the `patch` attribute of the file object which remains undefined for large files (due to limitations of the GitHub API).

**Comment by vojtechjelinek** [comment]
@seanlip Do we still want a feature like this?

**Comment by seanlip** [comment]
Hm, I'm not sure. Is it even possible to do a lint check for this? If so that sounds reasonable.

Maybe discuss with @DubeySandeep?

**Comment by seanlip** [comment]
I don't think this is needed, reviewers should be able to catch issues here if the pylint pragmas are unwarranted. Closing.

**Comment by vojtechjelinek** [comment]
@seanlip Hmm I find that having automated reminders about this might be nice. Firstly it reduces the amount of misses in the review and secondly a contributor can act on them before the reviewer even takes a pass. 

I agree that oppiabot might not be a good solution to this, but I think it might be possible to add this as part of the CodeQL checks.
