### ISSUE TITLE
Maintainers checklist is not relevant for non-fork branches

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppiabot#150]
See https://github.com/oppia/oppia/pull/11084#issuecomment-719022838. While most contributors create PRs that use forks and need to have that checkbox ticked, it's implicit for all branches created directly on the repository. We shouldn't raise this error except for branches on forks.

**Comment by gp201** [comment]
@jameesjohn please assign this issue to me.

**Comment by jameesjohn** [comment]
Done. You can start working on this.
