### ISSUE TITLE
Oppiabot shouldn't warn for CI failures that aren't required

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppiabot#151]
See: https://github.com/oppia/oppia/pull/11084#issuecomment-719022863. These CI failures are the new Google Cloud Build checks that are being built. They currently immediately and always fail for all PRs, but because they aren't required we can ignore them for PR submission. Oppiabot should also ignore non-required CI checks for the same reason.

**Comment by vojtechjelinek** [comment]
Not a priority rn, since these kind of messages doesn't work for PRs made from forks.
