### ISSUE TITLE
Oppiabot should make the CI error more actionable

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppiabot#152]
See https://github.com/oppia/oppia/pull/11084#issuecomment-719022863. Currently, Oppiabot instructs the user to report an issue. Could we maybe introduce a new Oppia issue template & pre-fill it out with the information Oppiabot noticed? E.g. it would be really helpful if we pre-populate the failing check, the PR number, and a link to the check results. I think Oppiabot has access to all of this, and I think you can pre-fill GitHub issues (see: https://github.com/isaacs/github/issues/99#issuecomment-443976302 though this just suggests filling in the body so maybe a template isn't needed).

**Comment by vojtechjelinek** [comment]
I don't think we should prefill an issue for the flaky tests, we already track the flaky tests through our automated tests logger/restarter.

**Comment by BenHenning** [comment]
I think one issue with the current flow is it's not clear to PR authors how to proceed when they encounter a flaky test. Is that something that we can make better with Oppiabot? I think the automatic tracking you mentioned is a bit of a blackbox for PR authors. I also don't see anyone follow up when a test does fail--it usually requires a maintainer to restart the test to unblock the PR.

**Comment by vojtechjelinek** [comment]
I think the situation with tests is a bit better now and they are usually automatically restarted. The other problem with implementing this is that GitHub doesn't create events on tests completion/fail for PRs from forked repositories.

**Comment by seanlip** [comment]
@vojtechjelinek Is it actually possible to act on this issue? If not, let's close it.
