### ISSUE TITLE
The CHANGELOG error isn't quite correct

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppiabot#153]
See https://github.com/oppia/oppia/pull/11084#issuecomment-719022790. Some PRs legitimately do not need to have a changelog, so we should have a way to opt out of the error (e.g. maybe by having a label like 'CHANGELOG: N/A' or something).

**Comment by jameesjohn** [comment]
Wouldn't the 'miscellaneous' changelog label suffice here?

**Comment by vojtechjelinek** [comment]
@jameesjohn We do not have that label anymore it seems, this can be probably just about adding the lable on the oppia repo right?

**Comment by vojtechjelinek** [comment]
I have added 'PR CHANGELOG: Miscellaneous -- @vojtechjelinek' label
