### ISSUE TITLE
Oppiabot should merge PRs if they qualify to be merged

### ISSUE THREAD

**Issue by vojtechjelinek** [oppia/oppiabot#160]
When PR has:

- all required tests passing
- all reviews
- LGTM label
- no DO NOT MERGE label

the Oppiabot should try to merge it. This would help with merging PRs that are just waiting for some tests to pass. There are existing solutions for this as GitHub Actions so we might use these.

[Dec 2020] The issue is that the GitHub events 'check_run' and 'check_suite' are not fired for completed tests when the PR is made from a fork, so we cannot use these for merging the PRs, we can have a periodic check that would check for the requirements above.

**Comment by vojtechjelinek** [comment]
GitHub introduced the auto merge feature in December so this has a lower priority now.

**Comment by SAEb-ai** [comment]
@vojtechjelinek @jameesjohn  Can I take up this issue?
Thanks!

**Comment by SAEb-ai** [comment]
@vojtechjelinek @jameesjohn Can I take up this issue?
Thanks!

**Comment by nlok5923** [comment]
@vojtechjelinek @jameesjohn i would like to try this issue.

**Comment by seanlip** [comment]
This is low priority due to the auto-merge feature. Let's close it.
