### ISSUE TITLE
Change tagged person when adding new models

### ISSUE THREAD

**Issue by vojtechjelinek** [oppia/oppiabot#161]
The comment for newly added models should tag @vojtechjelinek and not Ankita.
![image](https://user-images.githubusercontent.com/10142938/100395607-e355f180-3041-11eb-999d-b340a868b6f0.png)

Check for other places where Ankita is mentioned.

**Comment by jameesjohn** [comment]
Closing this as it was fixed as a part of #165 and has been deployed to heroku.
