### ISSUE TITLE
Feature request: enforcing TODOs

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppiabot#163]
The Oppia codebases require TODOs in code to be of the form ``TODO(#1234)`` where ``#1234`` corresponds to an issue number. Enforcing the format falls under static analysis and is something that the dev workflow team should look into adding. That being said, there's one aspect of TODO enforcement that Oppiabot is in an exclusively unique position to manage: making sure that issues aren't closed if there are lingering TODOs for them. I think the following could be really useful:
1. Having Oppiabot reopen issues if it detects that there are any additional TODOs open for that issue after the issue is closed by someone, then mentioning where those TODOs are in code
2. Having some mechanism for Oppiabot to specify what TODOs correspond to the issue (e.g. maybe by at-mentioning Oppiabot and asking it?)

**Comment by Naman-1234** [comment]
@BenHenning  Sir , Could you elobarate in this topic and tell me do you want TODO as a label or in Code. If you are suggesting them in code, Will Maintainer write TODO in the code or anything else. Please elobarate.

**Comment by BenHenning** [comment]
Hi,

This issue is specifically referring to tracking TODOs in code & ensuring
their corresponding GitHub issues stay open if there are still TODOs left.
For example, see TODOs in Oppia web codebase:
https://github.com/oppia/oppia/search?q=todo.

Does this help clarify?

**Comment by Naman-1234** [comment]
@BenHenning  That helps but still need a thing or two regarding clarification, Like who will add those TODO comments. (Author, Maintainer or Are you suggesting something else). And basically Sir you are saying that if the file changed by the author has TODO or not, THat we need to check. Have I got this right this far?
This issue seems to be helpful and interesting,  after getting clarity, I would like to work on this sir.

**Comment by Naman-1234** [comment]
@vojtechjelinek and @jameesjohn Sir Could you help out here. This issue really seems interesting to me and I would like to work on this one, Could you bring some light on the things that should be achieved by this issue.Thanks.

**Comment by seanlip** [comment]
Superseded by #316. I don't think we need the "ask Oppiabot" functionality mentioned in the 2nd point, contributors can just search for it.
