### ISSUE TITLE
Add test to ensure that bot doesn't gets triggred with "@{{username}} PTAL" comment

### ISSUE THREAD

**Issue by DubeySandeep** [oppia/oppiabot#174]
We have added `"{{Question/comment}} @{{reviewer_username}} PTAL"` test in the PR template ([ref](https://github.com/oppia/oppia/pull/11291/files#r546254529)).

Through this issue, we are expecting to add a unit test to make sure that oppia bot doesn't get triggered anytime with the above pattern.

**Comment by vojtechjelinek** [comment]
@DubeySandeep What do you exactly mean by the issue? What should the tests exactly check for?

**Comment by DubeySandeep** [comment]
I just wanted to have a unit test to ensure that oppiaBot doesn't assign contributors if the comments are around the text "{{Question/comment}} @{{reviewer_username}} PTAL". [This test will help us to ensure in future the oppiaBot doesn't get triggered with the PR template comments.]

**Comment by mridul-netizen** [comment]
Can i work on this one?

**Comment by mridul-netizen** [comment]
@DubeySandeep @vojtechjelinek I'm expecting this 
`describe(
    'when author asks some question/comment and asks reviewer to ptal',
    () `
`=> {
        beforeEach(async () => {`
`   pushPayload.payload.forced = false;
            await robot.receive(pushPayload);
          });`
`
          it('should not comment on pull request', () => {
            expect(github.issues.createComment).not.toHaveBeenCalled();
          }); 
    });`to be added in the `checkPullRequestReviewSpec.js` file but I'm not sure.

**Comment by mridul-netizen** [comment]
this is the regex expression I made for testing it `/^([a-z0-9\s]+ @\s*\w+\s* [pP][tT][aA][lL])/gm` you can test it [here](https://regex101.com/r/pqLiss/1)

**Comment by vojtechjelinek** [comment]
@mridul-netizen Looks good to me.

**Comment by Ayushsunny** [comment]
Hello @vojtechjelinek sir, is this issue still persist?

**Comment by vojtechjelinek** [comment]
@mridul-netizen Is still working on this issue.
