### ISSUE TITLE
Investigate issue with Oppiabot's comments

### ISSUE THREAD

**Issue by jameesjohn** [oppia/oppiabot#175]
Oppiabot's comment when a new user gets added to the code owners file is unreadable and looks incorrect. This needs to be investigated and fixed appropriately.

For context, see https://github.com/oppia/oppia/pull/11478#issuecomment-749875175, https://github.com/oppia/oppia/pull/11478#issuecomment-749886142.

**Comment by b2pacific** [comment]
I want to work on this issue. @jameesjohn can you assign this to me?

**Comment by jameesjohn** [comment]
Hi @b2pacific, I think this issue might be a bit complex for a first-time contributor. You might want to look into https://github.com/oppia/oppiabot/issues/198.

**Comment by nlok5923** [comment]
@jameesjohn sir it currently takes the latest updated code owners and then it appends all the  file whose codeowners has changed to the same comment.

Sir i am interested in this issue please can  you let me know what should be the actual behaviour

**Comment by Naman-1234** [comment]
@jameesjohn  and @vojtechjelinek Sir I would like to work on this issue, Could you Please assign me this one. Thanks.

**Comment by seanlip** [comment]
Duplicate of #236 .
