### ISSUE TITLE
Oppiabot does not assign author after pull request has been approved

### ISSUE THREAD

**Issue by jameesjohn** [oppia/oppiabot#176]
In some pull requests, oppiabot does not assign the appropriate user to merge the pull request even after adding the LGTM label.

See https://github.com/oppia/oppia/pull/11376, https://github.com/oppia/oppia/pull/11316.

__Expected Behaviour__

Oppiabot should assign the PR author if they have merging privileges or assign the project owner from the changelog label to merge the pull request if the PR author doesn't have merging privileges.

**Comment by riyasingh1004** [comment]
@jameesjohn I would like to work on this issue.

**Comment by SAEb-ai** [comment]
@vojtechjelinek @jameesjohn Can I take up this issue.

**Comment by vojtechjelinek** [comment]
@SAEb-ai Riya is already assigned to this issue.

**Comment by SAEb-ai** [comment]
@vojtechjelinek Okay. Thanks!
