### ISSUE TITLE
Modify Oppiabot comment during periodic check

### ISSUE THREAD

**Issue by jameesjohn** [oppia/oppiabot#177]
Oppiabot periodically goes through all pull requests and assign the appropriate users. When oppiabot is unable to figure out who the appropriate assignees are, it flags it and mentions the core maintainers. See https://github.com/oppia/oppia/pull/11405#issuecomment-749405670.

This message needs to be rephrased to something better.

**Comment by vojtechjelinek** [comment]
I would say something like "@… I cannot decide what to do with this PR, please assign people manually." And maybe you can also tag yourself or maybe tag the person responsible for Oppiabot right now to investigate this.

**Comment by HarshKhilawala** [comment]
@jameesjohn @vojtechjelinek  Would like to work on this one too!

**Comment by jameesjohn** [comment]
Sure @HarshKhilawala 
You have been assigned the issue.
