### ISSUE TITLE
Bot should remove the "Stale Build" label once a new commit is pushed

### ISSUE THREAD

**Issue by DubeySandeep** [oppia/oppiabot#179]
Currently, the Oppia bot adds a "Stale Build" label to the PRs where the PR CI builds ran 2+ days ago. But even if someone pushes new changes to the PR the Oppia bot doesn't remove the "Stale build" label.

Through this issue, we are expecting to remove the "Stale Build" label once a PR gets updated.

**Comment by DubeySandeep** [comment]
@vojtechjelinek @jameesjohn, will it be possible to fix this quickly? Though it's not blocking anyone new-contributors are finding this confusing. Thanks! :)

**Comment by jameesjohn** [comment]
Yes @DubeySandeep
I'll look into this tomorrow.

**Comment by DubeySandeep** [comment]
Hi @jameesjohn, any update on this issue? Do you have a rough ETA of when this can be resolved? :)

**Comment by SAEb-ai** [comment]
@vojtechjelinek @jameesjohn I think this thing still happens. See(https://github.com/oppia/oppia/pull/12370)
