### ISSUE TITLE
Cron job to ping codeowners who has not reviewed assigned PRs within 24 hrs.  

### ISSUE THREAD

**Issue by DubeySandeep** [oppia/oppiabot#182]
This is a feature request to send an email to the reviewers if they haven't reviewed the assigned PRs within 24 (or 36) hrs. ccin'g dev-workflow team or org admin. The reviewer receiving this email should be expected to respond to the email within the next 12 hrs. with the status of assigned PRs.

**Comment by DubeySandeep** [comment]
@jameesjohn , I'm not sure whether oppiaBot can do the following things:
  1. Send email to recipients
  2. Run Cron jobs
  
 Do you think it will be possible for oppiaBot to have this feature?

**Comment by jameesjohn** [comment]
1. I'm not sure it would be nice to have oppiabot send emails to users.
2. Yes, oppiabot can rn Cron jobs.

**Comment by DubeySandeep** [comment]
> I'm not sure it would be nice to have oppiabot send emails to users.

Can you please add your thoughts on why it won't be nice? [I just wanted to understand the thoughts behind it.] :)

**Comment by Naman-1234** [comment]
@vojtechjelinek  Sir I would like to work on this issue.

**Comment by Naman-1234** [comment]
@vojtechjelinek  Sir Can you assign me this issue please.

**Comment by vojtechjelinek** [comment]
Done.

**Comment by Naman-1234** [comment]
@vojtechjelinek  Sir Sorry I am disturbing you Could you tell me how should I check whether feature implemented by me is working or not. Or basically How the written functions are responding. In such a way it would be much easier for me to understand codebase.

**Comment by vojtechjelinek** [comment]
@jameesjohn can help with this.

**Comment by jameesjohn** [comment]
Hi @Naman-1234, you can follow the [getting started](https://github.com/oppia/oppiabot#getting-started) section on the read me to deploy your version of oppiabot, and then you can test the feature in a local repository of your choice.

**Comment by vojtechjelinek** [comment]
@DubeySandeep Hi, as of now we only plan to implement pings on the PR itself, how important is it to also send emails?

**Comment by seanlip** [comment]
This is currently being handled through Sandeep's bot, so we can close this issue.
