### ISSUE TITLE
Message asking project lead to merge the PR should have info on why they are expected to merge other's PR 

### ISSUE THREAD

**Issue by DubeySandeep** [oppia/oppiabot#187]
**Current situation:**
When the author doesn't have the rights to merge a PR then oppiaBot asks the team lead to merge the PR:
```
Hi @<team-lead>, this PR is ready to be merged. Before you merge it, please make sure that there are no pending comments that require action from the author's end. Thanks!
```

**Suggestion:**

In general, we expect PR authors to get their PRs merged but if in any case, we are asking anyone else to merge the PR then the bot should add info about why they are asked to merge the PR.

**Comment by HarshKhilawala** [comment]
@jameesjohn @vojtechjelinek Please assign me this issue.

**Comment by jameesjohn** [comment]
Done.
You can start working on the issue.
