### ISSUE TITLE
Remove LGTM label if changes are requested.

### ISSUE THREAD

**Issue by gp201** [oppia/oppiabot#198]
If after the LGTM label is placed, a reviewer request for changes then the LGTM label must be removed.
Ref: [Link](https://github.com/oppia/oppia/pull/11701#pullrequestreview-579995313)

**Comment by gp201** [comment]
@jameesjohn PTAL

**Comment by b2pacific** [comment]
@jameesjohn I'll work on this issue, please assign this to me.

**Comment by jameesjohn** [comment]
Done.
You can start working on this @b2pacific.

**Comment by b2pacific** [comment]
@jameesjohn  I made a PR, but one of the tests(frontend test) failed and I'm not sure why. Can you help me out?

**Comment by Naman-1234** [comment]
@vojtechjelinek Sir As told by you in the PR, I am commenting on the issue. Could you please assign me.Thanks.
