### ISSUE TITLE
Add a GitHub Action for the "PR: don't merge…" labels

### ISSUE THREAD

**Issue by vojtechjelinek** [oppia/oppiabot#205]
Couldn't we add a GitHub actions check that fails on the presence of the "PR: don't merge…" labels & make it a required check?

I think we can listen for label changes, too, so that particular workflow re-runs if we did that, I'm pretty sure auto-merge would respect it since it has to match normal merging criteria (which for us is approvals + all required tests passing).

**Comment by vojtechjelinek** [comment]
Hi @jameesjohn, do you think this would be possible to do? Do you see any problems that could arise from implementing this?

**Comment by jameesjohn** [comment]
Yes, this is very possible to achieve. I'm not sure of any problems that could arise from this, but do you think the action should be written in oppiabot GitHub actions or in the main oppia repo?

**Comment by vojtechjelinek** [comment]
I guess similar to the action that is used to checking issue labels.

**Comment by jameesjohn** [comment]
Right, okay.
