### ISSUE TITLE
Remove Sean from server job admins

### ISSUE THREAD

**Issue by jameesjohn** [oppia/oppiabot#207]
Following @seanlip's comment on https://github.com/oppia/oppia/pull/11967#issuecomment-790909157, he needs to be removed from the list of server job admins. 

The list of server job admins can be found in the `userWhitelist.json` file.

**Comment by SAEb-ai** [comment]
@jameesjohn Can I take up this issue.

**Comment by jameesjohn** [comment]
Sure.

**Comment by Mayank-gaur** [comment]
Hi! I want to work on this issue.  @jameesjohn  can you please guide me how can I get started with the issue?

**Comment by jameesjohn** [comment]
Hi @Mayank-gaur, this issue has already been assigned to @SAEb-ai
