### ISSUE TITLE
oppiabot tag @undefined to add changelog label

### ISSUE THREAD

**Issue by nlok5923** [oppia/oppiabot#213]
refer pr [#12228](https://github.com/oppia/oppia/pull/12228)
This happens when there are multiple codeowners

@vojtechjelinek @jameesjohn  PTAL

**Comment by nlok5923** [comment]
@vojtechjelinek i want to work on this issue.

**Comment by vojtechjelinek** [comment]
@nlok5923 Sure I have assigned you.

**Comment by nlok5923** [comment]
@vojtechjelinek sir i think this issue has been already addressed [here](https://github.com/oppia/oppiabot/pull/206) but no included in release.

**Comment by vojtechjelinek** [comment]
Yeah, thanks, James already released the PR yesterday.

**Comment by jameesjohn** [comment]
Closing since the PR got released.
