### ISSUE TITLE
Oppiabot should remove the PR from the blocking bugs milestone

### ISSUE THREAD

**Issue by SAEb-ai** [oppia/oppiabot#217]
Oppiabot should remove the blocking bugs milestone from the PR's if any contributor misktakenely adds the PR to the blocking bugs milestone.
For reference : See(https://github.com/oppia/oppia/pull/12281) 

@vojtechjelinek @jameesjohn PTAL. Can this be possible?. If yes please assign this issue to me.

**Comment by vojtechjelinek** [comment]
Makes sense. I have assigned you.

**Comment by seanlip** [comment]
I'm closing this as very low priority because it doesn't happen often and can easily be remediated if it does.
