### ISSUE TITLE
ping pr author that there's already a pr targetting same issue

### ISSUE THREAD

**Issue by nlok5923** [oppia/oppiabot#222]
There are certain cases when contributor create pr for the issue which is already targeted by another previously opened pr in that case we should ping the subsequent pr author that there already exist a pr (with pr no) targeting the same issue.

@vojtechjelinek  @jameesjohn sir please provide your opinions on this feature.

**Comment by nlok5923** [comment]
i would like to work on it if this feature is valid.

**Comment by vojtechjelinek** [comment]
Hmm, I think it might make sense but I see a few potential problems and also think that it is not that important. Any opinion @jameesjohn?

**Comment by jameesjohn** [comment]
Yeah
I can see some problems with multiple PRs fixing one issue, as that is the case in some issues like the angular migration issues.
And also, it is not common for us to have contributors creating PRs for the same issue unless it is one with multiple tasks.

So I don't think this is really important.

**Comment by nlok5923** [comment]
@jameesjohn  sir what i thought is as we are having predefined pr title to it will be easy for us to find out whether the pr is solemnly solving the issue or it is solving the subpart of it.

**Comment by vojtechjelinek** [comment]
I mean it would be possible but it is not important and it doesn`t occur that frequently.

**Comment by seanlip** [comment]
This is not important for the reasons @jameesjohn mentioned. We need to focus on the most important issues, so we're not doing this.
