### ISSUE TITLE
Setting Reminders

### ISSUE THREAD

**Issue by riyasingh1004** [oppia/oppiabot#224]
Users can set reminders by using /remind in a comment. I think reminders will be useful for reviewers as well as contributors who are working on various things. [ Here ](https://probot.github.io/apps/reminders/) is an example for such a reminder. I think this can be quite helpful.

@vojtechjelinek @jameesjohn  Do you think this can be implemented as a valid feature.

**Comment by vojtechjelinek** [comment]
I guess it can but I think it is not a priority and it would be a bit complicated.
