### ISSUE TITLE
Oppiabot should add PR Don't merge:STATE BUILD label again. 

### ISSUE THREAD

**Issue by SAEb-ai** [oppia/oppiabot#225]
Oppiabot should re add the `PR Don't merge:STATE BUILD` if any collaborator mistakenly remove the label even before updating the branch with the recent changes in develop.
For ref: See(https://github.com/oppia/oppia/pull/11844#issuecomment-774325391)

@vojtechjelinek @jameesjohn Does it make sense?
Thanks!

**Comment by vojtechjelinek** [comment]
Yep, sounds good.

**Comment by nlok5923** [comment]
@vojtechjelinek @jameesjohn sir this issue seems quite interesting I would like to work on it.

**Comment by vojtechjelinek** [comment]
@nlok5923 Go ahead.

**Comment by nlok5923** [comment]
@vojtechjelinek as periodic checks are scheduled with interval of 1 day so oppiabot will automatically add `Don't merge:STATE BUILD` label after 1day interval. to resolve this issue i think we can reduce the interval but still reducing interval may break other features .

@vojtechjelinek  @jameesjohn  sir please can you let me know any other approach as i had also not able to find any event associated with altering pr label.

**Comment by jameesjohn** [comment]
> to resolve this issue I think we can reduce the interval 

I don't think that is quite right.
We can listen on the `unlabeled` event, and if the label that got removed is the stale build label, we run the stale build check again and if the PR requires the label to be added, we add it back.

**Comment by jameesjohn** [comment]
You can check the work on preventing the removal of the critical label for more info.

https://github.com/oppia/oppiabot/blob/959b59c9ccc6cd1494b249f6b1fa11176258bbfc/lib/checkPullRequestLabels.js#L289-L320
