### ISSUE TITLE
Updating Year in CopyRight Policy from 2020 to 2021

### ISSUE THREAD

**Issue by Naman-1234** [oppia/oppiabot#231]
Currently, all the files containing copy-right policy in the comments in all the files show 2020. This should be updated to 2021 as there is been three months since starting of year 2021.

@vojtechjelinek, Sir If this is a valid issue. I would like to work on this one. Could you assign me Please. Thanks.

**Comment by vojtechjelinek** [comment]
No need for this, the year only needs to be recent on files created this year.

**Comment by Naman-1234** [comment]
Ok Sir. No Problem.
