### ISSUE TITLE
Reminding user if he/she gets assigned to more than 5 issues.

### ISSUE THREAD

**Issue by Naman-1234** [oppia/oppiabot#232]
Basically if a user gets assigned to more than 5 issues which are currently open, then oppiabot will create a comment on that issue to remind user(If you want we can let oppiabot remove assignment but that might not be right). 
This will bring equity in the projects. Because in this way all will get a chance to contribute.

@vojtechjelinek Sir Please let me know. If this is a valid issue. I will be happy to work on this one. In that case could you assign me please. Thanks.

**Comment by vojtechjelinek** [comment]
There is no need for a feature like this, we currently have quite a lot of other stuff for Oppiabot that needs to be prioritized.
