### ISSUE TITLE
Improve oppiabot ownership transfer comment message

### ISSUE THREAD

**Issue by nlok5923** [oppia/oppiabot#236]
currently it looks like this: 
refer [this](https://github.com/oppia/oppia/pull/11478#issuecomment-749875175)
![image](https://user-images.githubusercontent.com/56120084/112761811-9ea38c80-901a-11eb-897b-bd0be0cd92f2.png)
After changes:
![image](https://user-images.githubusercontent.com/56120084/112762038-6b153200-901b-11eb-8b81-b625d37acff9.png)

**Comment by nlok5923** [comment]
@vojtechjelinek @jameesjohn sir i would like to make a quick fix for this issue.

**Comment by nlok5923** [comment]
@vojtechjelinek @jameesjohn i would like to work on this issue if this is seems to a valid issue.

**Comment by seanlip** [comment]
Let's definitely fix this. It's not readable currently. Thanks @nlok5923 for pointing it out!

**Comment by seanlip** [comment]
Not sure if this is relevant any more since we do codeowners by teams now.
