### ISSUE TITLE
Oppiabot is tagging the author again even after the changelog level was added.

### ISSUE THREAD

**Issue by SAEb-ai** [oppia/oppiabot#240]
Oppiabot is tagging the author again even after the changelog level was added.
For ref: See(https://github.com/oppia/oppia/pull/12364)

Does it seem to be an issue with oppiabot @vojtechjelinek @jameesjohn PTAL.

**Comment by nlok5923** [comment]
yeah i also think this issue need to be addressed oppiabot should not comment for adding label if label already exist @vojtechjelinek @jameesjohn i would like fix this issue.

**Comment by nlok5923** [comment]
@vojtechjelinek @jameesjohn i would like to fix this issue.

**Comment by jameesjohn** [comment]
Done.

**Comment by nlok5923** [comment]
@jameesjohn i think we can close this issue because it is very rare to occur.

**Comment by seanlip** [comment]
Closing for now. Let's reopen if it reoccurs.
