### ISSUE TITLE
Oppiabot is not adding PR Don't Merge:Has Merge Conflicts label to some PR's

### ISSUE THREAD

**Issue by SAEb-ai** [oppia/oppiabot#244]
**Describe the bug**
Oppiabot is not adding PR Don't Merge:Has Merge Conflicts label to some PR's

**To Reproduce**
 1. Go to https://github.com/oppia/oppia/pull/12402'

**Observed behavior**
Oppiabot is not adding PR Don't Merge:Has Merge Conflicts label to some PR's

**Expected behavior**
Oppiabot should add the label. 

@vojtechjelinek @jameesjohn PTAL. Does it seem to be an issue with oppiabot or I am misinterpreting it?

**Comment by vojtechjelinek** [comment]
Hmm, yeah it seems like it.

**Comment by jameesjohn** [comment]
It seems the PR had a merge conflict at the time of creation and oppiabot is not currently checking for merge conflicts upon creating the PR.

**Comment by nlok5923** [comment]
@jameesjohn should we enable merge conflict check once pull request open event got triggered.

**Comment by seanlip** [comment]
Yes, let's add that check at time of opening too.

**Comment by himanshusharma27** [comment]
I want to work on this issue . Please assign me this issue .

**Comment by seanlip** [comment]
We actually want to get rid of these notifications altogether since we now have a merge queue. So, closing this issue.
