### ISSUE TITLE
Oppiabot should close a PR if junk commits are present.

### ISSUE THREAD

**Issue by gp201** [oppia/oppiabot#250]
**Is your feature request related to a problem? Please describe.**
If there are more than 5 junk commits present in the PR then close the PR and ask the contributor to open a new one.

**Describe the solution you'd like**
Check if any of the commit hashes are present in the develop branch. If more than 5 are present then close the branch and ask the contributor to open a new one.

**Describe alternatives you've considered**

**Additional context**
Junk commits refer to commits that have already been merged in a previous PR but again appear in a new PR.

**Comment by vojtechjelinek** [comment]
We decided that this is not a priority rn.
