### ISSUE TITLE
Fix: Ensure Oppiabot verifies CLA work for Android too

### ISSUE THREAD

**Issue by nlok5923** [oppia/oppiabot#256]
@jameesjohn @vojtechjelinek sir please can you elaborate on this issue on which i am assigned currently.

**Comment by BenHenning** [comment]
I'm also interested in knowing what's needed here. The CLA check is currently enabled & working on Oppia Android, but I know we were considering how to make the CLA check more robust (e.g. to fail if it can't verify that someone has signed it). That shouldn't be specific to Android, though. @jameesjohn / @vojtechjelinek am I missing anything?

/cc @anandwana001 as well

**Comment by vojtechjelinek** [comment]
Not sure what this is about? We should have a CI job that will verify CLA enabled in a day or two. Waiting just for Sandeep's approval and the Sean will enable it on web and probably Android too.

**Comment by BenHenning** [comment]
Is there a PR or issue I can follow along on for that @vojtechjelinek? I can enable it on Android once it's available.

**Comment by jameesjohn** [comment]
This issue is to update the CLA check to respond with a different link that is specific for the android repository.
See https://docs.google.com/document/d/1MjnEZvelFY7yaHbWyXei7S3UxEE708EnVBy17bOYNhg/edit#bookmark=id.k5eeqb5rabz8

**Comment by nlok5923** [comment]
@jameesjohn can you please let me know which link i need to add in oppiabot's comment.

**Comment by nlok5923** [comment]
@jameesjohn can you please let me know which link i need to add in oppiabot's comment.

**Comment by jameesjohn** [comment]
https://github.com/oppia/oppia-android/wiki#onboarding-instructions

**Comment by jameesjohn** [comment]
You can use that link.
