### ISSUE TITLE
Github action bot should close the PR if the author has not signed the CLA

### ISSUE THREAD

**Issue by DubeySandeep** [oppia/oppiabot#279]
OppiaBot use to close the PR if the PR author has not signed the CLA. We migrated the CLA check to the Github-actions as the OppiaBot feature was not reliable. 

Currently, the github-action bot is not closing the PR in such a situation. Through this issue, we want to ensure that OppiaBot closes such PRs.

**Comment by DubeySandeep** [comment]
@vojtechjelinek @gp201 Can we prioritize fixing this issue? (it seems like a regression)

Also, I came to know that we still have the oppiaBot's CLA check in the system, is that expected? (I think we should remove the OppiaBot's CLA check completely as it's not reliable and make sure that github-action's bot works perfectly for the CLA check!)

**Comment by vojtechjelinek** [comment]
We have the GitHub Action enabled, it is 100 % reliable. @gp201 Can we modify the action to also close the PR? And remove the legacy CLA code?

**Comment by gp201** [comment]
Currently, Oppiabot handles CLA check for issues also ([checkIssueAssignee.js](https://github.com/oppia/oppiabot/blob/master/lib/checkIssueAssignee.js)). Should this be disabled. 
The CLA check using GitHub actions is not enabled for the Oppiabot repository. It is currently relying on the Oppiabot CLA check.

**Comment by vojtechjelinek** [comment]
@seanlip Hey, do we care about CLA if someone is assigned to an issue? Also, can it happen that someone without CLA gets assigned to issue? Since I imagine the person must already created some PRs so they probably also signed the CLA.

@gp201 Can we enable the Action for oppiabot repo too?

**Comment by seanlip** [comment]
I don't think we care about that -- e.g. someone can be assigned to an issue if they need to provide follow-up information. See e.g. here: https://github.com/oppia/oppia/issues/13719

Note that Oppiabot didn't comment on that issue FYI.
