### ISSUE TITLE
Come up with a robust definition of “stale”

### ISSUE THREAD

**Issue by lilithxxx** [oppia/oppiabot#28]
Come up with a robust definition of “stale” that works for our codebase, and make oppiabot handle this correctly so that PRs like [#6138](https://github.com/oppia/oppia/pull/6138) are not missed. 
The third party stale app needs to be modified.

**Comment by apb7** [comment]
The stale check seems to be running fine since we've reduced the number of days for a PR to be considered stale. Due to this, the number of open PRs in the code base is below 30. Therefore, we do not need to modify the definition of "stale". Thanks!
