### ISSUE TITLE
 For every PR open > 72 hours, go through all review comments

### ISSUE THREAD

**Issue by lilithxxx** [oppia/oppiabot#29]
For every PR open > 72 hours, go through all review comments; if there’s no comment by a listed reviewer yet, assign oppia-dev as an assignee of the task. This is recorded in metrics and the reviewer is pinged. This needs to be checked on a daily basis

**Comment by apb7** [comment]
We (probably) will not require this check if the review cycle functions properly and issues #34 and #35 are resolved. Thanks!

**Comment by ankita240796** [comment]
This isn't required -- will be handled in #35.
