### ISSUE TITLE
[Oppia Android] Request to enable post-merge sync notifications

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppiabot#291]
Can we enable the post-merge sync notifications in Oppia Android? That is, having Oppiabot automatically update PRs with a label to indicate that they need to be synced with develop if a PR is merged with the "PR: require post-merge sync to HEAD" label. Should this already work out of the box, or does it need to be enabled in Oppiabot & redeployed? I couldn't find any repo-side configuration for it in Oppia web.

**Comment by seanlip** [comment]
@BenHenning On looking at the oppiabot code I think this is implemented generically, so it should work out of the box if I'm not mistaken. 

I've added the label to Android. Could you please try it and see if it works? If not then please reopen this issue (which I'm closing in the meantime).

Thanks!

**Comment by seanlip** [comment]
OK, sg, thanks -- will keep this closed for now, then.
