### ISSUE TITLE
Check for PTAL

### ISSUE THREAD

**Issue by lilithxxx** [oppia/oppiabot#30]
For every PR which has been open for > 72 hours, work from the most recent comment backwards to identify the last “streak” of review comments by the author of the PR. (If the last comment isn’t by the author of the PR, skip this PR. Also ignore any comments by codecov or oppiabot.) Then, see if this last streak of comments includes the string “PTAL”. If more than 72 hours has elapsed from the “PTAL” comment, then assign oppia-dev to the task. This is recorded in metrics and the reviewer is pinged. This needs to be checked on a daily basis

**Comment by apb7** [comment]
We will not require this check once Issue #34 and #35 are resolved and the new review cycle has been put in place. Therefore, closing this, thanks!
