### ISSUE TITLE
Disable stale check on Android repo

### ISSUE THREAD

**Issue by vojtechjelinek** [oppia/oppiabot#311]
Don't close stuff as stale if the reviewer hasn't reviewed. For details ask someone from the Android repo.

**Comment by seanlip** [comment]
This should be implemented for Web too, right?

**Comment by vojtechjelinek** [comment]
@seanlip I guess so, although I'm not really sure about the impact as I didn't notice this for a long time. I think we are fairly safe as we do have measures in place (Sandeeps notifier) that make sure that the reviewers review in time.
