### ISSUE TITLE
Make message about who can add "good first issue" labels more clear

### ISSUE THREAD

**Issue by vojtechjelinek** [oppia/oppiabot#312]
Make sure its message is clear about who can add "good first issue" labels (currently just says Sandeep but that's not true).

**Comment by seanlip** [comment]
We should also manage this using a GitHub team instead of individual people.

**Comment by himanshusharma27** [comment]
I want to work on this issue . Please assign me this issue .

**Comment by seanlip** [comment]
@himanshusharma27 Per the guidance at https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#choosing-a-good-first-issue, please provide an explanation of what your PR will do (with names of files you're changing, what you plan to change in each file, etc.). If it looks good, we can assign you to this issue.

Please also follow the other instructions on that wiki page if you have not yet done so. Thanks!

**Comment by himanshusharma27** [comment]
Hii @seanlip ! In the constants.js  folder  There appears to be an inconsistency in the number of items in the checksWhitelist object for the oppia repository.To fix this, you can remove one item from the array under [openEvent]: 
After removing one item from the array under [openEvent], the number of items in each array should match, resolving the inconsistency.

**Comment by krishnarao22** [comment]
I'll take a look at this @U8NWXD

**Comment by vojtechjelinek** [comment]
@seanlip @U8NWXD Who should be the people who can add good first issue labels? Ideally can we create a GH team for this?
