### ISSUE TITLE
Auto-assign reviewers for a PR when created, and give clearer instructions to contributors on how to make that assignment happen.

### ISSUE THREAD

**Issue by seanlip** [oppia/oppiabot#320]
**Is your feature request related to a problem? Please describe.**

I noticed that this PR got auto-closed recently: https://github.com/oppia/oppia/pull/18065 . On examining it, it seems that there were two process failures:

(a) When the PR was opened, Oppiabot didn't automatically assign the codeowners (should be @gp201 and @seanlip)
(b) When Oppiabot asked the author to assign the required reviewers for the PR, it didn't explain how to do it (both in terms of figuring out who those reviewers are, and explaining how to send a message to Oppiabot to do the assignment since new contributors cannot assign reviewers directly).

I'm not sure if the original contributor is actually tracking the PR, but AFAICT they never seemed to reach out, though they did keep merging develop into the PR. Maybe they didn't know who to reach out to.

In any case, this flow seems to be suboptimal and has resulted in a "waste" of a PR, as well as a potentially frustrating experience for the contributor.

**Describe the solution you'd like**

Ideally, Oppiabot does (a), but we should also update the message to do (b).

Consider also making it clearer to folks that they should reach out to the dev workflow team or on Discussions if their PR hasn't seen any action after 2 days. Maybe Oppiabot can ping the dev workflow team directly.

**Describe alternatives you've considered**

We could do a subset of the above, depending on what is feasible and makes sense.

**Comment by prafulbbandre** [comment]
This issue might only be faced by new contributor's so as sanjay, patel and I are working on helping new contributors so I think one of us should get ping by the oppiabot so that they could get explained in a much simple way.
Correct me.
Thanks!

**Comment by gp201** [comment]
Ok, I believe that this is a bug. (same with https://github.com/oppia/oppiabot/issues/321). I think adding a wait before line 44 would fix the issue. Looks like before Github assigns the reviewers, oppiabot thinks there are no reviewers assigned. Also, please note that if contributors face any issue regarding PR's not moving forward, they can open a GitHub Discussion.

https://github.com/oppia/oppiabot/blob/02f075d7008c1c25c5fa89aff18307e5ec8deb2f/lib/checkPullRequestLabels.js#L38-L66

**Comment by gp201** [comment]
#330 should fix the issue
