### ISSUE TITLE
Remove the "please merge from develop" notification, since it's unnecessary

### ISSUE THREAD

**Issue by seanlip** [oppia/oppiabot#324]
**Describe the bug**

Oppiabot occasionally asks developers to merge develop into their branch due to staleness. However, this is now unnecessary since we are using a merge queue. The aim of this issue is to get rid of this "merge notification" since it is no longer needed.

**Observed behavior**
Oppiabot occasionally creates a comment saying "Please update this pull request with the latest changes from develop."

**Expected behavior**
Oppiabot should stop publishing such comments.

**Screenshots**
![Screenshot from 2023-06-21 12-41-13](https://github.com/oppia/oppiabot/assets/10575562/0d4025d3-469b-4d68-8adf-b72de88ad82d)

**Comment by lalitkumawat1m** [comment]
hey @seanlip, I am willing to work on this issue, please assign me this issue.

**Comment by seanlip** [comment]
@lalitkumawat1m Per the guidance at https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#choosing-a-good-first-issue, please provide an explanation of what your PR will do (with names of files you're changing, what you plan to change in each file, etc.). If it looks good, we can assign you to this issue.

Please also follow the other instructions on that wiki page if you have not yet done so. Thanks!

**Comment by gp201** [comment]
#331 should fix the issue
