### ISSUE TITLE
Automatically notify devs (by commenting on their PR) if their CI build fails

### ISSUE THREAD

**Issue by apb7** [oppia/oppiabot#36]
Add a check to automatically notify devs (by commenting on their PR) if their CI build fails. (Maybe look at https://github.com/apps/ci-reporter).

**Comment by seanlip** [comment]
In addition to doing this, could we also please add a message that points the developer to the relevant part of https://github.com/oppia/oppia/wiki/If-your-build-fails (based on which checks are failing)?  (We should also probably update that page to include separate troubleshooting sections for the different types of checks.)

**Comment by kevinlee12** [comment]
We can definitely do that!

**Comment by ankita240796** [comment]
This is fixed by #110.
