### ISSUE TITLE
Ensure that each PR has a changelog label at time-of-merge

### ISSUE THREAD

**Issue by apb7** [oppia/oppiabot#38]
As a fix for #19, we've decided to take incremental steps to ensure that each PR has a changelog label. Therefore, if a PR does not have a changelog label, the bot will ping the author to fix it but will not close the PR.
A repo check, similar to TravisCI should be implemented as a next step, if the former does not work, to ensure that each PR has a changelog label at time-of-merge. Oppiabot should be more of a helper rather than an enforcer, in this case.

**Comment by jameesjohn** [comment]
Currently, oppiabot has been implemented to also assign the PR author if the PR does not have a changelog label at the time of creation, and there have been no concerns with the current implementation.
