### ISSUE TITLE
Update npm packages

### ISSUE THREAD

**Issue by kevinlee12** [oppia/oppiabot#41]
Our npm packages are quite out date, this issue is to log the upgrade of the npm packages.

**Comment by sdhiman99** [comment]
Hi! I'm new here and would like to contribute to this repo. How do I start? Can I take up this issue, if it's still relevant?

**Comment by kevinlee12** [comment]
thanks for your interest! Oppiabot as it stands is being deprecated and we’re migrating to something else. Perhaps @ankita240796 can point you to something else in this domain if you are still interested.

**Comment by kevinlee12** [comment]
Closing since we need to move to a new Oppiabot written from scratch.
