### ISSUE TITLE
Close PRs on force push

### ISSUE THREAD

**Issue by kevinlee12** [oppia/oppiabot#43]
We take force-pushing a PR under review quite seriously -- it makes it hard for reviewers to go through the changes made in the PR.
The aim of this issue is to add a double-confirmation message in the pre-push checks before a developer is able to force-push commits onto a PR.
We can have two confirmation messages with a `YES` or `NO` something along the following lines:
- `You are trying to force-push commits onto a feature branch. If there is a pull request using this branch, which is under review, this will overwrite history on GitHub and make the incremental changes harder to review. Are you sure that you want to force-push?`
- If the answer for the above question is `YES`, then ask: `Are you really sure that you want to force-push?`
- Only if the answer to the above question is `YES`, allow force-push.
(Please note that we're open for ideas here!)

See the following on how to detect force-pushes: [SO Post](https://stackoverflow.com/questions/10319110/how-to-detect-a-forced-update) and [Sample script](https://github.com/kyanny/git-hooks-detect-force-update)

**Comment by shubhamjadon** [comment]
@kevinlee12 I would like to work on this.

**Comment by kevinlee12** [comment]
Sure, though would you mind doing it is github actions? Please also do it on the oppia repo (https://github.com/oppia/oppia)

**Comment by shubhamjadon** [comment]
I achieved the following functioning with the help of git hooks(pre-push hook) which is working correctly. 
For github actions: Well i think i am not able to clearly understand how i can achieve this using github actions as from what i understood github actions run on github and git push will be done from local machine so to trigger force-push we must use hooks. I don't know how can we link both(github actions and hooks). So, can you please let me know what am i missing?

**Comment by kevinlee12** [comment]
We want to avoid using git hooks since those can easily be overridden by the user. Also, the point is not to prevent contributors from force pushing, they can do that **only** if they don't have a PR open. As a starter for Github Actions, I'd recommend looking at https://github.com/features/actions.

**Comment by shubhamjadon** [comment]
@kevinlee12 where will confirmation messages appear??(At which stage)

**Comment by kevinlee12** [comment]
All actions will occur when the PR is open, so everything will be on the Github side.

**Comment by ankita240796** [comment]
Fixed in #101.
