### ISSUE TITLE
Remove usage of probot-stale

### ISSUE THREAD

**Issue by ankita240796** [oppia/oppiabot#62]
Replace probot stale with probot scheduler since we are currently using a fork of probot/stale which isn't updated and is using old dependencies of probot, probot-config which have deprecated functions.

**Comment by jameesjohn** [comment]
Probot stale has been updated, and we resolved to keep probot stale since it has a different interval with what we currently use for other periodic checks, and it might be complex to add the functionality to oppiabot.
