### ISSUE TITLE
Add support for oppia-android

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppiabot#64]
This is a feature request to update & set up the bot to work on https://github.com/oppia/oppia-android. I think right now all we need is the CLA tracking support, but we may request/add additional, Android-specific functionality in the future.

I'm happy to make the changes if folks point me in the right direction. :)

**Comment by BenHenning** [comment]
After looking through the code, perhaps we could introduce some sort of configuration file to specify which features are enabled for the bot, and configuration parameters for those features? That way, I can create an Android-specific configuration file & deploy the bot with just CLA checking enabled.

**Comment by ankita240796** [comment]
Hi @BenHenning, sorry for the late reply. 

I think we will need the following changes as you have suggested:

- Update the config [here](https://github.com/oppia/oppiabot/blob/master/index.js) to contain two lists which specify the checks for android/main repo
- For each event, we can check the repo and based on that trigger the check from the checklist.

Thanks!
