### ISSUE TITLE
Consider switching to yarn for js package installs

### ISSUE THREAD

**Issue by kevinlee12** [oppia/oppiabot#7]
Since yarn is a more intelligent package manager with much more functionality than npm and installs every package that npm can, it is worth researching a move to use yarn.

**Comment by kevinlee12** [comment]
not a high priority, but worth looking into when there is time.

**Comment by seanlip** [comment]
I think we discussed this and decided not to do it, so I'm closing this.

That said, @kevinlee12, please feel free to reopen if I'm misremembering. Thanks!
