### ISSUE TITLE
Feature Request: Auto submit PRs with a particular label

### ISSUE THREAD

**Issue by vinitamurthi** [oppia/oppiabot#73]
A lot of times we have PRs where all the reviewers have LGTM'ed but the continuous integration tests are still running. On oppia-web, we label those PRs with a 'PR: LGTM' label and the author is expected to merge the PR once the tests pass. 
It may be useful to have oppia bot scan PRs with this label, and check if the tests are complete and have passed. If the tests have passed, it can automatically submit that PR. 
I am not sure if Github allows bots to submit PRs, and also we need to think about the final commit that is dependent on who merges the PR.

**Comment by vojtechjelinek** [comment]
We had this in the tracker for oppiabot and decided not to do this: Rationale for not doing: sometimes PRs by trusted authors are given "LGTM but please fix this before merging"; this would circumvent that.
