### ISSUE TITLE
Check for yarn.lock when package.json is changed

### ISSUE THREAD

**Issue by ankita240796** [oppia/oppiabot#77]
Oppiabot should check that whenever package.json is changed, yarn.lock must be accompanied (but not vice versa).

Refer: https://github.com/oppia/oppia/pull/8931#discussion_r413481107

**Comment by jameesjohn** [comment]
I thought this is done by the pre commit check

**Comment by vojtechjelinek** [comment]
File an issue in oppia/oppia.

**Comment by vojtechjelinek** [comment]
@jameesjohn Could you file issue on https://github.com/oppia/oppia and then close this, please.

**Comment by jameesjohn** [comment]
The issue has been created at https://github.com/oppia/oppia/issues/11130
