### ISSUE TITLE
Fix detection of PRs that include jobs

### ISSUE THREAD

**Issue by seanlip** [oppia/oppiabot#90]
The handling of job-related PRs by oppiabot is broken. Please revert and fix accordingly. For more details, please see the comment at https://github.com/oppia/oppia/pull/9546#issuecomment-646406716.

Also, please note that the formatting is off. Make sure you have one blank line separating each paragraph.

/cc @ankita240796

**Comment by ankita240796** [comment]
Hi @seanlip, I agree that the name of jobs is not being displayed correctly and that should be fixed but regarding filling of form, I think we should fill a form before the merge even if they aren't rn actively since that will ensure that the job does not have any errors. WDYT?

**Comment by seanlip** [comment]
But we don't run prod validation audit jobs in that way, right?

**Comment by seanlip** [comment]
oh wait -- are you saying, we should actively test those too, though we currently don't?

**Comment by seanlip** [comment]
If so I'm ok with that. Though the form is currently not geared towards that...

**Comment by ankita240796** [comment]
Yes, actually the reason behind that is that we got so many bugs while running existing prod jobs which wouldn't be there in the first place if we had tested them before the merge.

Re the form, I can update it, making the question optional: are you targeting this for a release and if the answer is yes, then only we show this question and add the response to the jobs list.

**Comment by seanlip** [comment]
Ah -- yeah maybe what you can do is, make the form such that it branches based on the multiple-choice answer. Something like that should work.

**Comment by ankita240796** [comment]
Sure, I will make the changes and share that with you!

Meanwhile @jameesjohn can you please fix the issue such that the names are shown correctly, Thanks!

**Comment by jameesjohn** [comment]
Okay
Working on this.
